//! `knit run eject`: materialize the transform's lift as an editable,
//! committed `docker-compose.knit.yml` — the exit from transform mode into
//! contract mode. The transform's knowledge (which paths are repos, which
//! ports are published, which service is the database) is written out as
//! `${KNIT_*}` interpolations, so when the automatic lift mishandles a stack
//! the fix is editing a file in the repo, never patching knit:
//!
//! - paths into tracked repos become `${KNIT_CHECKOUT_<REPO>}` /
//!   `${KNIT_SRC_<REPO>}`; the workspace root becomes `${KNIT_ROOT}`; the
//!   user's home becomes `${HOME}`
//! - every published host port becomes `${KNIT_PORT_<SERVICE>:-<original>}`,
//!   and textual references to it follow; the `:-` default doubles as the
//!   allocation base `knit run up` scans for
//! - the configured shared-database service is kept but gated behind the
//!   `bundle-db` profile and wired to `${KNIT_DB_*}`, so the one file serves
//!   both database modes: `shared` attaches to the dev database, `bundle`
//!   starts the profiled service per bundle
//!
//! Once the file exists, compose-file detection prefers it and the transform
//! stops applying to that repo.

use crate::config::{ProjectRuntime, ProjectRuntimeDatabase, RuntimeMode};
use crate::plan::{StackPlan, CONTRACT_COMPOSE_CANDIDATES};
use crate::support::{self, env_var_suffix, out};
use crate::transform;
use crate::yaml;
use crate::RuntimeContext;
use anyhow::{bail, Context, Result};
use serde_json::{json, Map, Value};
use std::fs;
use std::path::{Path, PathBuf};

pub(crate) fn run_eject(
    ctx: &RuntimeContext,
    runtime: &ProjectRuntime,
    plans: Vec<StackPlan>,
    force: bool,
) -> Result<()> {
    let inputs = EjectInputs::from_context(ctx, runtime);
    let mut wrote = false;
    for plan in &plans {
        if plan.mode == RuntimeMode::Contract {
            println!(
                "{} {} already runs a contract compose file: {}",
                out::heading("Skip:"),
                out::repo(&plan.repo.id),
                out::path(plan.compose.display())
            );
            continue;
        }
        let target = plan.checkout.join(CONTRACT_COMPOSE_CANDIDATES[0]);
        if target.exists() && !force {
            bail!(
                "{} already exists. Pass --force to overwrite it.",
                target.display()
            );
        }

        let mut config = transform::resolve_compose_config(&plan.compose, &plan.repo.source_path)?;
        let summary = eject_compose(&mut config, &inputs)?;
        let text = format!(
            "{}{}",
            header(&plan.compose, summary.database_service.as_deref()),
            yaml::to_yaml(&config)
        );
        fs::write(&target, text)
            .with_context(|| format!("failed to write {}", target.display()))?;

        println!(
            "{} {} {}",
            out::heading("Ejected:"),
            out::repo(&plan.repo.id),
            out::path(target.display())
        );
        for (service, variable, base) in &summary.ports {
            println!(
                "{} {} {} (base {})",
                out::muted("Port:"),
                service,
                variable,
                base
            );
        }
        if let Some(service) = &summary.database_service {
            println!(
                "{} `{service}` gated behind the bundle-db profile, wired to KNIT_DB_*",
                out::muted("Database:")
            );
        }
        wrote = true;
    }
    if wrote {
        println!(
            "{}",
            out::muted(
                "Next: review the generated file, adjust what the lift got wrong, and commit it. `knit run up` now runs it as-is (contract mode)."
            )
        );
    }
    Ok(())
}

fn header(source_compose: &Path, database_service: Option<&str>) -> String {
    // Variable names are written without `${` on purpose: a plain mention is
    // neither a contract opt-in for mode detection nor a port-scan hit.
    let source = source_compose
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "the repo compose file".to_string());
    let mut text = format!(
        "# Knit bundle runtime stack — generated by `knit run eject` from {source}.\n\
         # Edit freely and commit; this file owns the service topology, build args,\n\
         # and app environment from now on.\n\
         #\n\
         # `knit run up` runs this file as-is (contract mode) as compose project\n\
         # `knit-run-<bundle>` with the runtime environment contract injected:\n\
         #\n\
         #   KNIT_ROOT / KNIT_BUNDLE     workspace root and bundle id\n\
         #   KNIT_CHECKOUT_<REPO>        absolute checkout path per repo\n\
         #   KNIT_SRC_<REPO>             the same path relative to KNIT_ROOT\n\
         #   KNIT_REV_<REPO>             HEAD revision of that checkout\n\
         #   KNIT_PORT_<SERVICE>         allocated host port per published service;\n\
         #                               the `:-` default is the allocation base\n\
         #   KNIT_DB_MODE / _HOST / _PORT / _NAME / _HOST_PORT   database wiring\n"
    );
    if let Some(service) = database_service {
        text.push_str(&format!(
            "#\n\
             # In `bundle` database mode knit activates the `bundle-db` profile so the\n\
             # `{service}` service starts per bundle; in `shared` mode the stack attaches\n\
             # to the dev database described by the KNIT_DB_* variables.\n"
        ));
    }
    text.push('\n');
    text
}

/// What the caller needs to know about an ejected config, for the printout.
pub(crate) struct EjectSummary {
    /// `(service, variable, base)` per published port.
    pub(crate) ports: Vec<(String, String, u16)>,
    pub(crate) database_service: Option<String>,
}

/// Everything path- and database-shaped the parameterization maps against.
/// Repo paths are the *source* checkouts: eject runs on the source compose
/// shape, and the variables resolve to bundle checkouts at `up` time.
pub(crate) struct EjectInputs {
    root: PathBuf,
    home: Option<PathBuf>,
    repos: Vec<(String, PathBuf)>,
    database: Option<ProjectRuntimeDatabase>,
}

impl EjectInputs {
    fn from_context(ctx: &RuntimeContext, runtime: &ProjectRuntime) -> Self {
        let mut repos: Vec<(String, PathBuf)> = Vec::new();
        for (id, path) in ctx
            .repos
            .iter()
            .map(|repo| (repo.id.clone(), repo.source_path.clone()))
            .chain(ctx.extra_checkouts.iter().cloned())
        {
            if repos.iter().any(|(existing, _)| *existing == id) {
                continue;
            }
            if let Ok(canonical) = support::canonicalize(&path) {
                repos.push((id, canonical));
            }
        }
        Self {
            root: support::canonicalize(&ctx.root).unwrap_or_else(|_| ctx.root.clone()),
            home: std::env::var_os("HOME")
                .map(PathBuf::from)
                .and_then(|home| support::canonicalize(&home).ok()),
            repos,
            database: runtime.database.clone(),
        }
    }
}

/// Parameterize a resolved compose config (the JSON output of `docker compose
/// config` against the source repo) in place into the `KNIT_*` contract.
pub(crate) fn eject_compose(config: &mut Value, inputs: &EjectInputs) -> Result<EjectSummary> {
    transform::strip_stack_identity(config);

    // Database first, so the database's published port never becomes a
    // KNIT_PORT pool and references to it aren't rewritten as app ports.
    let database_service = parameterize_database(config, inputs);

    let Some(services) = config
        .get_mut("services")
        .and_then(|services| services.as_object_mut())
    else {
        bail!("compose config has no services");
    };

    let mut port_map: Vec<(u16, String)> = Vec::new();
    let mut summary_ports: Vec<(String, String, u16)> = Vec::new();
    for (service_name, service) in services.iter_mut() {
        let Some(service) = service.as_object_mut() else {
            continue;
        };
        service.remove("container_name");

        if let Some(build) = service.get_mut("build").and_then(Value::as_object_mut) {
            eject_build(build, inputs);
        }
        if let Some(volumes) = service.get_mut("volumes").and_then(Value::as_array_mut) {
            for volume in volumes {
                eject_volume(volume, inputs);
            }
        }

        if let Some(entries) = service.get_mut("ports").and_then(Value::as_array_mut) {
            let mut first = true;
            for entry in entries {
                let Some((old, target)) = published_port(entry) else {
                    continue;
                };
                // One variable per service; extra published ports are
                // disambiguated by their container port.
                let suffix = if first {
                    env_var_suffix(service_name)
                } else {
                    format!("{}_{}", env_var_suffix(service_name), target.unwrap_or(old))
                };
                first = false;
                set_published(entry, &format!("${{KNIT_PORT_{suffix}:-{old}}}"));
                summary_ports.push((service_name.clone(), format!("KNIT_PORT_{suffix}"), old));
                port_map.push((old, suffix));
            }
        }
    }

    // Textual references to published host ports in app configuration follow
    // their service's variable, so cross-service URLs stay wired per bundle.
    for service in services.values_mut() {
        let Some(service) = service.as_object_mut() else {
            continue;
        };
        let rewire = |values: &mut Map<String, Value>| {
            for value in values.values_mut() {
                let Some(text) = value.as_str() else {
                    continue;
                };
                let mut rewritten = text.to_string();
                for (old, suffix) in &port_map {
                    for host in ["localhost", "127.0.0.1", "host.docker.internal"] {
                        rewritten = rewritten.replace(
                            &format!("{host}:{old}"),
                            &format!("{host}:${{KNIT_PORT_{suffix}:-{old}}}"),
                        );
                    }
                }
                if rewritten != text {
                    *value = Value::String(rewritten);
                }
            }
        };
        if let Some(environment) = service
            .get_mut("environment")
            .and_then(Value::as_object_mut)
        {
            rewire(environment);
        }
        if let Some(args) = service
            .get_mut("build")
            .and_then(Value::as_object_mut)
            .and_then(|build| build.get_mut("args"))
            .and_then(Value::as_object_mut)
        {
            rewire(args);
        }
    }

    Ok(EjectSummary {
        ports: summary_ports,
        database_service,
    })
}

/// Turn the configured database service into the profile-gated pattern: kept
/// in the file behind the `bundle-db` profile (started only in `bundle`
/// database mode, with an ephemeral database), published on
/// `${KNIT_DB_HOST_PORT}`, its dependents wired to `${KNIT_DB_HOST}` /
/// `${KNIT_DB_PORT}` / `${KNIT_DB_NAME}` — which resolve to the shared dev
/// database in `shared` mode and to the profiled service in `bundle` mode.
fn parameterize_database(config: &mut Value, inputs: &EjectInputs) -> Option<String> {
    let database = inputs.database.as_ref()?;
    let service_name = database.service.clone()?;
    let container_port = database.container_port.unwrap_or(5432);

    let services = config
        .get_mut("services")
        .and_then(|services| services.as_object_mut())?;
    let db_service = services
        .get_mut(&service_name)
        .and_then(Value::as_object_mut)?;

    db_service.insert("profiles".to_string(), json!(["bundle-db"]));
    // Per-bundle databases are ephemeral: no data volume to leak between
    // bundles or collide with the dev stack's.
    db_service.remove("volumes");
    if let Some(entries) = db_service.get_mut("ports").and_then(Value::as_array_mut) {
        for entry in entries {
            if published_port(entry).is_some() {
                set_published(entry, "${KNIT_DB_HOST_PORT}");
            }
        }
    }
    if !database.name.is_empty() {
        replace_in_strings(db_service, &database.name, "${KNIT_DB_NAME}");
    }

    let old_addr = format!("{service_name}:{container_port}");
    let new_addr = "${KNIT_DB_HOST}:${KNIT_DB_PORT}";
    let container_port_text = container_port.to_string();

    for (name, remaining) in services.iter_mut() {
        if *name == service_name {
            continue;
        }
        let Some(remaining) = remaining.as_object_mut() else {
            continue;
        };

        // Keep the dependency, but optional: it only exists when the
        // bundle-db profile activates the service.
        match remaining.get_mut("depends_on") {
            Some(Value::Object(depends)) => {
                if let Some(entry) = depends
                    .get_mut(&service_name)
                    .and_then(Value::as_object_mut)
                {
                    entry.insert("required".to_string(), Value::Bool(false));
                }
            }
            Some(depends @ Value::Array(_)) => {
                let names: Vec<String> = depends
                    .as_array()
                    .unwrap()
                    .iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect();
                if names.iter().any(|entry| *entry == service_name) {
                    let mut map = Map::new();
                    for entry in names {
                        let optional = entry == service_name;
                        let mut spec = Map::new();
                        spec.insert(
                            "condition".to_string(),
                            Value::String("service_started".to_string()),
                        );
                        if optional {
                            spec.insert("required".to_string(), Value::Bool(false));
                        }
                        map.insert(entry, Value::Object(spec));
                    }
                    *depends = Value::Object(map);
                }
            }
            _ => {}
        }

        let mut rewired = false;
        let mut rewire = |values: &mut Map<String, Value>| {
            for (key, value) in values.iter_mut() {
                let Some(text) = value.as_str() else {
                    continue;
                };
                let replacement = if text == service_name {
                    Some("${KNIT_DB_HOST}".to_string())
                } else if text == container_port_text && key.to_lowercase().contains("port") {
                    Some("${KNIT_DB_PORT}".to_string())
                } else if !database.name.is_empty() && text == database.name {
                    Some("${KNIT_DB_NAME}".to_string())
                } else if text.contains(&old_addr) {
                    let mut rewritten = text.replace(&old_addr, new_addr);
                    if !database.name.is_empty() {
                        rewritten = rewritten.replace(&database.name, "${KNIT_DB_NAME}");
                    }
                    Some(rewritten)
                } else {
                    None
                };
                if let Some(replacement) = replacement {
                    *value = Value::String(replacement);
                    rewired = true;
                }
            }
        };
        if let Some(environment) = remaining
            .get_mut("environment")
            .and_then(Value::as_object_mut)
        {
            rewire(environment);
        }
        if let Some(args) = remaining
            .get_mut("build")
            .and_then(Value::as_object_mut)
            .and_then(|build| build.get_mut("args"))
            .and_then(Value::as_object_mut)
        {
            rewire(args);
        }
        // In shared mode KNIT_DB_HOST is typically host.docker.internal;
        // Linux containers only resolve it with the gateway alias.
        if rewired && !remaining.contains_key("extra_hosts") {
            remaining.insert(
                "extra_hosts".to_string(),
                json!(["host.docker.internal:host-gateway"]),
            );
        }
    }

    transform::retain_referenced_volumes(config);
    Some(service_name)
}

/// Where a build context landed, which decides how context-relative values
/// (dockerfile, path-shaped build args) are re-expressed.
enum ContextBase {
    Repo(String),
    Root,
    Other,
}

fn classify(path: &Path, inputs: &EjectInputs) -> ContextBase {
    let canonical = support::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    if let Some((id, _)) = longest_repo_match(&canonical, inputs) {
        return ContextBase::Repo(id);
    }
    if canonical.strip_prefix(&inputs.root).is_ok() {
        return ContextBase::Root;
    }
    ContextBase::Other
}

fn eject_build(build: &mut Map<String, Value>, inputs: &EjectInputs) {
    let original_context = build
        .get("context")
        .and_then(Value::as_str)
        .map(PathBuf::from);
    let base = original_context
        .as_ref()
        .map(|context| classify(context, inputs))
        .unwrap_or(ContextBase::Other);

    if let Some(context) = &original_context {
        if let Some(expr) = var_path(context, inputs) {
            build.insert("context".to_string(), Value::String(expr));
        }
    }
    if let Some(contexts) = build
        .get_mut("additional_contexts")
        .and_then(Value::as_object_mut)
    {
        for value in contexts.values_mut() {
            if let Some(path) = value.as_str() {
                if let Some(expr) = var_path(Path::new(path), inputs) {
                    *value = Value::String(expr);
                }
            }
        }
    }

    let Some(context) = original_context else {
        return;
    };
    if let Some(dockerfile) = build.get("dockerfile").and_then(Value::as_str) {
        if let Some(expr) = context_relative_var(dockerfile, &context, &base, inputs) {
            build.insert("dockerfile".to_string(), Value::String(expr));
        }
    }
    if let Some(args) = build.get_mut("args").and_then(Value::as_object_mut) {
        for value in args.values_mut() {
            if let Some(text) = value.as_str() {
                if let Some(expr) = context_relative_var(text, &context, &base, inputs) {
                    *value = Value::String(expr);
                }
            }
        }
    }
}

/// Re-express a context-relative value (dockerfile, path-shaped build arg)
/// against the parameterized context. Only values that resolve to an existing
/// path inside a tracked repo are rewritten — everything else (revisions,
/// flags, plain strings) is left alone:
///
/// - context is `${KNIT_ROOT}`: root-relative `${KNIT_SRC_<REPO>}/...`
/// - context is the same repo: the relative value already lands in the
///   checkout (worktrees mirror the repo layout), leave it
/// - anywhere else: absolute `${KNIT_CHECKOUT_<REPO>}/...`
fn context_relative_var(
    value: &str,
    context: &Path,
    base: &ContextBase,
    inputs: &EjectInputs,
) -> Option<String> {
    let candidate = PathBuf::from(value);
    if candidate.is_absolute() {
        return var_path(&candidate, inputs);
    }
    // canonicalize collapses `..` hops and doubles as the existence guard.
    let resolved = support::canonicalize(context.join(&candidate)).ok()?;
    let (repo_id, source) = longest_repo_match(&resolved, inputs)?;
    let suffix = resolved.strip_prefix(&source).ok()?;
    match base {
        ContextBase::Repo(id) if *id == repo_id => None,
        ContextBase::Root => Some(join_var(
            &format!("KNIT_SRC_{}", env_var_suffix(&repo_id)),
            suffix,
        )),
        _ => Some(join_var(
            &format!("KNIT_CHECKOUT_{}", env_var_suffix(&repo_id)),
            suffix,
        )),
    }
}

fn eject_volume(volume: &mut Value, inputs: &EjectInputs) {
    match volume {
        Value::Object(entry) => {
            if entry.get("type").and_then(Value::as_str) != Some("bind") {
                return;
            }
            if let Some(source) = entry.get("source").and_then(Value::as_str) {
                if let Some(expr) = var_path(Path::new(source), inputs) {
                    entry.insert("source".to_string(), Value::String(expr));
                }
            }
        }
        Value::String(text) => {
            if let Some((source, rest)) = text.split_once(':') {
                if let Some(expr) = var_path(Path::new(source), inputs) {
                    *text = format!("{expr}:{rest}");
                }
            }
        }
        _ => {}
    }
}

/// Express an absolute path as a `${KNIT_*}` interpolation: the containing
/// repo's checkout (longest prefix wins), else the workspace root, else the
/// user's home. Paths outside all three stay literal.
fn var_path(path: &Path, inputs: &EjectInputs) -> Option<String> {
    let canonical = support::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    if let Some((id, source)) = longest_repo_match(&canonical, inputs) {
        let suffix = canonical.strip_prefix(&source).ok()?;
        return Some(join_var(
            &format!("KNIT_CHECKOUT_{}", env_var_suffix(&id)),
            suffix,
        ));
    }
    if let Ok(suffix) = canonical.strip_prefix(&inputs.root) {
        return Some(join_var("KNIT_ROOT", suffix));
    }
    if let Some(home) = &inputs.home {
        if let Ok(suffix) = canonical.strip_prefix(home) {
            return Some(join_var("HOME", suffix));
        }
    }
    None
}

fn longest_repo_match(path: &Path, inputs: &EjectInputs) -> Option<(String, PathBuf)> {
    let mut best: Option<(usize, String, PathBuf)> = None;
    for (id, source) in &inputs.repos {
        if path.strip_prefix(source).is_ok() {
            let depth = source.components().count();
            if best.as_ref().is_none_or(|(d, _, _)| depth > *d) {
                best = Some((depth, id.clone(), source.clone()));
            }
        }
    }
    best.map(|(_, id, source)| (id, source))
}

fn join_var(variable: &str, suffix: &Path) -> String {
    let rest: Vec<String> = suffix
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect();
    if rest.is_empty() {
        format!("${{{variable}}}")
    } else {
        format!("${{{variable}}}/{}", rest.join("/"))
    }
}

/// The `(host, container)` ports of a published port entry, long or short
/// syntax. Entries whose host side is not a literal number (already an
/// interpolation) report `None`.
fn published_port(entry: &Value) -> Option<(u16, Option<u16>)> {
    match entry {
        Value::Object(port) => {
            let old = match port.get("published")? {
                Value::String(text) => text.parse::<u16>().ok()?,
                Value::Number(number) => u16::try_from(number.as_u64()?).ok()?,
                _ => return None,
            };
            let container = port
                .get("target")
                .and_then(Value::as_u64)
                .and_then(|n| u16::try_from(n).ok());
            Some((old, container))
        }
        Value::String(text) => {
            let (host, rest) = text.split_once(':')?;
            let old = host.parse::<u16>().ok()?;
            let container = rest
                .split('/')
                .next()
                .and_then(|part| part.parse::<u16>().ok());
            Some((old, container))
        }
        _ => None,
    }
}

fn set_published(entry: &mut Value, expr: &str) {
    match entry {
        Value::Object(port) => {
            port.insert("published".to_string(), Value::String(expr.to_string()));
        }
        Value::String(text) => {
            let original = text.clone();
            if let Some((_, rest)) = original.split_once(':') {
                *text = format!("{expr}:{rest}");
            }
        }
        _ => {}
    }
}

fn replace_in_strings(values: &mut Map<String, Value>, from: &str, to: &str) {
    for value in values.values_mut() {
        replace_in_value(value, from, to);
    }
}

fn replace_in_value(value: &mut Value, from: &str, to: &str) {
    match value {
        Value::String(text) => {
            if text.contains(from) {
                *text = text.replace(from, to);
            }
        }
        Value::Array(items) => {
            for item in items {
                replace_in_value(item, from, to);
            }
        }
        Value::Object(map) => {
            for entry in map.values_mut() {
                replace_in_value(entry, from, to);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn temp_root() -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "knit-eject-test-{}-{:?}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
        ));
        for repo in ["knithub", "knithub-frontend", "gloss-web-ui"] {
            std::fs::create_dir_all(root.join(repo)).unwrap();
        }
        std::fs::create_dir_all(root.join("knithub/priv")).unwrap();
        std::fs::write(root.join("knithub/Dockerfile.worktree"), "FROM scratch").unwrap();
        std::fs::write(root.join("knithub-frontend/Dockerfile"), "FROM scratch").unwrap();
        support::canonicalize(&root).unwrap()
    }

    fn inputs(root: &Path) -> EjectInputs {
        EjectInputs {
            root: root.to_path_buf(),
            home: None,
            repos: vec![
                ("knithub".to_string(), root.join("knithub")),
                (
                    "knithub-frontend".to_string(),
                    root.join("knithub-frontend"),
                ),
                ("gloss-web-ui".to_string(), root.join("gloss-web-ui")),
            ],
            database: Some(ProjectRuntimeDatabase {
                service: Some("db".to_string()),
                name: "knithub_dev".to_string(),
                ..Default::default()
            }),
        }
    }

    fn resolved_config(root: &str) -> Value {
        json!({
            "name": "knithub",
            "services": {
                "db": {
                    "container_name": "knithub-db",
                    "image": "postgres:17",
                    "environment": {"POSTGRES_DB": "knithub_dev"},
                    "ports": [{"mode": "ingress", "target": 5432, "published": "5436", "protocol": "tcp"}],
                    "volumes": [{"type": "volume", "source": "db-data", "target": "/var/lib/postgresql/data"}],
                    "healthcheck": {"test": ["CMD-SHELL", "pg_isready -d knithub_dev"]}
                },
                "backend": {
                    "container_name": "knithub-backend",
                    "build": {
                        "context": root,
                        "dockerfile": "knithub/Dockerfile.worktree",
                        "args": {"KNITHUB_SRC": "knithub", "KNIT_REV": "main"}
                    },
                    "environment": {
                        "DATABASE_HOST": "db",
                        "DATABASE_PORT": "5432",
                        "DATABASE_NAME": "knithub_dev",
                        "DATABASE_URL": "postgres://u:p@db:5432/knithub_dev",
                        "KNITHUB_ALLOWED_ORIGINS": "http://localhost:5173"
                    },
                    "ports": [{"mode": "ingress", "target": 4000, "published": "4000", "protocol": "tcp"}],
                    "volumes": [
                        {"type": "bind", "source": root, "target": "/workspace"},
                        {"type": "bind", "source": format!("{root}/knithub/priv"), "target": "/app/priv"}
                    ],
                    "depends_on": {"db": {"condition": "service_healthy", "required": true}}
                },
                "frontend": {
                    "build": {
                        "context": format!("{root}/knithub-frontend"),
                        "dockerfile": "Dockerfile",
                        "args": {"GLOSS_SRC": "../gloss-web-ui"},
                        "additional_contexts": {"gloss-web-ui": format!("{root}/gloss-web-ui")}
                    },
                    "environment": {"VITE_KNITHUB_API_URL": "http://localhost:4000"},
                    "ports": [{"mode": "ingress", "target": 5173, "published": "5173", "protocol": "tcp"}],
                    "depends_on": ["backend"]
                }
            },
            "volumes": {"db-data": {"name": "knithub_db-data"}}
        })
    }

    #[test]
    fn eject_parameterizes_paths_ports_and_database() {
        let root = temp_root();
        let root_str = root.display().to_string();
        let inputs = inputs(&root);
        let mut config = resolved_config(&root_str);

        let summary = eject_compose(&mut config, &inputs).unwrap();

        // Stack identity is stripped.
        assert!(config.get("name").is_none());
        assert!(config["services"]["backend"]
            .get("container_name")
            .is_none());

        // Paths become contract interpolations: root context, root-relative
        // dockerfile and build arg, repo contexts, bind mounts.
        let backend_build = &config["services"]["backend"]["build"];
        assert_eq!(backend_build["context"], "${KNIT_ROOT}");
        assert_eq!(
            backend_build["dockerfile"],
            "${KNIT_SRC_KNITHUB}/Dockerfile.worktree"
        );
        assert_eq!(backend_build["args"]["KNITHUB_SRC"], "${KNIT_SRC_KNITHUB}");
        // Not a path: left alone.
        assert_eq!(backend_build["args"]["KNIT_REV"], "main");

        let frontend_build = &config["services"]["frontend"]["build"];
        assert_eq!(
            frontend_build["context"],
            "${KNIT_CHECKOUT_KNITHUB_FRONTEND}"
        );
        // In-repo dockerfile stays relative: worktrees mirror the layout.
        assert_eq!(frontend_build["dockerfile"], "Dockerfile");
        assert_eq!(
            frontend_build["args"]["GLOSS_SRC"],
            "${KNIT_CHECKOUT_GLOSS_WEB_UI}"
        );
        assert_eq!(
            frontend_build["additional_contexts"]["gloss-web-ui"],
            "${KNIT_CHECKOUT_GLOSS_WEB_UI}"
        );

        let backend_volumes = config["services"]["backend"]["volumes"].as_array().unwrap();
        assert_eq!(backend_volumes[0]["source"], "${KNIT_ROOT}");
        assert_eq!(
            backend_volumes[1]["source"],
            "${KNIT_CHECKOUT_KNITHUB}/priv"
        );

        // Published ports become KNIT_PORT variables with the original port
        // as the allocation-base default, and textual references follow.
        assert_eq!(
            config["services"]["backend"]["ports"][0]["published"],
            "${KNIT_PORT_BACKEND:-4000}"
        );
        assert_eq!(
            config["services"]["frontend"]["ports"][0]["published"],
            "${KNIT_PORT_FRONTEND:-5173}"
        );
        assert_eq!(
            config["services"]["backend"]["environment"]["KNITHUB_ALLOWED_ORIGINS"],
            "http://localhost:${KNIT_PORT_FRONTEND:-5173}"
        );
        assert_eq!(
            config["services"]["frontend"]["environment"]["VITE_KNITHUB_API_URL"],
            "http://localhost:${KNIT_PORT_BACKEND:-4000}"
        );
        assert_eq!(
            summary
                .ports
                .iter()
                .map(|(service, variable, base)| (service.as_str(), variable.as_str(), *base))
                .collect::<Vec<_>>(),
            vec![
                ("backend", "KNIT_PORT_BACKEND", 4000),
                ("frontend", "KNIT_PORT_FRONTEND", 5173),
            ]
        );

        // The database service is kept behind the bundle-db profile, wired to
        // KNIT_DB_*, with an ephemeral database.
        assert_eq!(summary.database_service.as_deref(), Some("db"));
        let db = &config["services"]["db"];
        assert_eq!(db["profiles"], json!(["bundle-db"]));
        assert_eq!(db["ports"][0]["published"], "${KNIT_DB_HOST_PORT}");
        assert!(db.get("volumes").is_none());
        assert_eq!(db["environment"]["POSTGRES_DB"], "${KNIT_DB_NAME}");
        assert_eq!(
            db["healthcheck"]["test"],
            json!(["CMD-SHELL", "pg_isready -d ${KNIT_DB_NAME}"])
        );
        assert!(config["volumes"].get("db-data").is_none());

        // Dependents are rewired to the database variables; the dependency
        // stays but becomes optional (only bundle mode starts the service).
        let backend_env = &config["services"]["backend"]["environment"];
        assert_eq!(backend_env["DATABASE_HOST"], "${KNIT_DB_HOST}");
        assert_eq!(backend_env["DATABASE_PORT"], "${KNIT_DB_PORT}");
        assert_eq!(backend_env["DATABASE_NAME"], "${KNIT_DB_NAME}");
        assert_eq!(
            backend_env["DATABASE_URL"],
            "postgres://u:p@${KNIT_DB_HOST}:${KNIT_DB_PORT}/${KNIT_DB_NAME}"
        );
        assert_eq!(
            config["services"]["backend"]["depends_on"]["db"]["required"],
            json!(false)
        );
        assert_eq!(
            config["services"]["backend"]["extra_hosts"],
            json!(["host.docker.internal:host-gateway"])
        );
        // The frontend never referenced the database: untouched.
        assert!(config["services"]["frontend"].get("extra_hosts").is_none());

        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn eject_without_database_config_leaves_db_service_as_app_service() {
        let root = temp_root();
        let root_str = root.display().to_string();
        let mut inputs = inputs(&root);
        inputs.database = None;
        let mut config = resolved_config(&root_str);

        let summary = eject_compose(&mut config, &inputs).unwrap();

        // No database config: the db service is an ordinary service with its
        // own KNIT_PORT pool and keeps its volume (isolated per bundle by the
        // compose project name).
        assert!(summary.database_service.is_none());
        let db = &config["services"]["db"];
        assert!(db.get("profiles").is_none());
        assert_eq!(db["ports"][0]["published"], "${KNIT_PORT_DB:-5436}");
        assert_eq!(db["volumes"][0]["source"], "db-data");
        assert!(config["volumes"].get("db-data").is_some());

        std::fs::remove_dir_all(root).unwrap();
    }
}
